export const feedbackForms = [
  {
    eventId: "EV001",
    included: true,
    generated: true,
    publishedAt: "2027-10-23T18:00:00.000Z",
    closedAt: null,
    questions: [
      {
        id: "CTF_Q1",
        question: "How would you rate the overall difficulty and quality of the CTF challenges?",
        type: "radio",
        options: ["Challenging & Well-Crafted", "Balanced", "Too Easy", "Needs Better Balance"],
      },
      {
        id: "CTF_Q2",
        question: "Which challenge categories did you find most engaging and educational?",
        type: "checkbox",
        options: ["Web Exploitation", "Reverse Engineering", "Cryptography", "Digital Forensics", "Binary Exploitation (Pwn)"],
      },
      {
        id: "CTF_Q3",
        question: "Was the CTF scoring platform, challenge deployment, and network connectivity stable?",
        type: "radio",
        options: ["Strongly Agree", "Agree", "Neutral", "Disagree"],
      },
      {
        id: "CTF_Q4",
        question: "Did the volunteer mentors provide prompt assistance during platform or venue issues?",
        type: "radio",
        options: ["Yes, immediately", "Somewhat helpful", "No assistance needed", "Needs Improvement"],
      },
      {
        id: "CTF_Q5",
        question: "What specific challenge categories or topics would you like to see in future CTF editions?",
        type: "textarea",
        options: [],
      },
    ],
    responses: [],
    analyticsReport: null,
    responseFile: null,
    responseSentToAdmin: false,
    reportSentToAdmin: false,
  },
  {
    eventId: "EV002",
    included: true,
    generated: true,
    publishedAt: null,
    closedAt: null,
    questions: [
      {
        id: "Q101",
        question: "How would you rate your prior knowledge of ethical hacking?",
        type: "radio",
        options: ["Beginner", "Intermediate", "Advanced"],
      },
      {
        id: "Q102",
        question: "Was the hands-on bug bounty demonstration practical?",
        type: "radio",
        options: ["Very Practical", "Moderately Practical", "Not Practical"],
      },
      {
        id: "Q103",
        question: "Which tools did you find most useful during the demo?",
        type: "checkbox",
        options: ["Burp Suite", "OWASP ZAP", "Nmap", "Sublist3r"],
      },
      {
        id: "Q104",
        question: "Did the mentor effectively resolve your technical queries?",
        type: "radio",
        options: ["Yes, completely", "Somewhat", "No"],
      },
      {
        id: "Q105",
        question: "What specific topics would you like to see in Part 2 of this bootcamp?",
        type: "textarea",
        options: [],
      },
    ],
    responses: [],
    analyticsReport: null,
    responseFile: null,
    responseSentToAdmin: false,
    reportSentToAdmin: false,
  },
  {
    eventId: "EV005",
    included: true,
    generated: true,
    publishedAt: "2027-08-05T13:00:00.000Z",
    closedAt: "2027-08-06T01:00:00.000Z",
    questions: [
      {
        id: "Q001",
        question: "How would you rate the overall quality of this session?",
        type: "radio",
        options: ["Excellent", "Good", "Average", "Poor"],
      },
      {
        id: "Q002",
        question: "Was the speaker explanation clear and easy to follow?",
        type: "radio",
        options: ["Strongly Agree", "Agree", "Neutral", "Disagree"],
      },
      {
        id: "Q003",
        question: "Which topics did you find most valuable?",
        type: "checkbox",
        options: ["Email Header Analysis", "Phishing Indicators", "MFA Setup", "Credential Harvesting Demos"],
      },
      {
        id: "Q004",
        question: "Would you recommend this workshop to other students?",
        type: "radio",
        options: ["Yes, definitely", "Maybe", "No"],
      },
      {
        id: "Q005",
        question: "What suggestions do you have for future cybersecurity events?",
        type: "textarea",
        options: [],
      },
    ],
    responses: [
      {
        id: "RESP001",
        name: "Jeny Patel",
        enrollment: "21012011001",
        branch: "IT",
        yearSem: "3rd Year",
        answers: {
          Q001: "Excellent",
          Q002: "Strongly Agree",
          Q003: ["Email Header Analysis", "Phishing Indicators"],
          Q004: "Yes, definitely",
          Q005: "Great session! Please organize a hands-on Wireshark lab next.",
        },
      },
      {
        id: "RESP002",
        name: "Archi Shah",
        enrollment: "21012011002",
        branch: "CE",
        yearSem: "3rd Year",
        answers: {
          Q001: "Good",
          Q002: "Agree",
          Q003: ["Phishing Indicators", "Credential Harvesting Demos"],
          Q004: "Yes, definitely",
          Q005: "The live attack simulations were very informative.",
        },
      },
      {
        id: "RESP003",
        name: "Meet Joshi",
        enrollment: "21012011003",
        branch: "ICT",
        yearSem: "2nd Year",
        answers: {
          Q001: "Excellent",
          Q002: "Strongly Agree",
          Q003: ["Email Header Analysis", "MFA Setup"],
          Q004: "Yes, definitely",
          Q005: "More time for Q&A would be great.",
        },
      },
      {
        id: "RESP004",
        name: "Riya Desai",
        enrollment: "21012011004",
        branch: "IT",
        yearSem: "4th Year",
        answers: {
          Q001: "Good",
          Q002: "Agree",
          Q003: ["Credential Harvesting Demos"],
          Q004: "Maybe",
          Q005: "Audio in the back rows of the seminar hall was a bit low.",
        },
      },
    ],
    analyticsReport: null,
    responseFile: null,
    responseSentToAdmin: false,
    reportSentToAdmin: false,
  },
];