export const tasks = [
  {
    id: "TSK001",
    eventId: "EV001",
    title: "Arrange VGEC Seminar Hall & seating layout",
    description: "Ensure 200 chairs and projection display are configured.",
    completed: true,
  },
  {
    id: "TSK002",
    eventId: "EV001",
    title: "Verify CTF platform servers & local Wi-Fi",
    description: "Test high-bandwidth network connectivity for participants.",
    completed: true,
  },
  {
    id: "TSK003",
    eventId: "EV001",
    title: "Prepare volunteer registration & continuous scanning desk",
    description: "Assign 4 volunteers with devices for QR attendee verification.",
    completed: false,
  },
  {
    id: "TSK004",
    eventId: "EV001",
    title: "Print participant badges & rulebooks",
    description: "Hard copies for emergency offline reference.",
    completed: false,
  },
  {
    id: "TSK005",
    eventId: "EV002",
    title: "Configure Computer Lab 3 workstations",
    description: "Pre-install Burp Suite and required proxy tools.",
    completed: true,
  },
  {
    id: "TSK006",
    eventId: "EV002",
    title: "Verify speaker presentation & audio system",
    description: "Coordinate with speaker Priya Patel.",
    completed: false,
  },
  {
    id: "TSK007",
    eventId: "EV009",
    title: "Reserve Seminar Hall 1 & mic system",
    description: "Coordinate with college administration for booking clearance.",
    completed: true,
  },
  {
    id: "TSK008",
    eventId: "EV009",
    title: "Coordinate banner display at main entrance",
    description: "Place TCF standee near the foyer.",
    completed: false,
  },
  {
    id: "TSK009",
    eventId: "EV010",
    title: "Check Lab 2 network firewall settings",
    description: "Allow outbound traffic for web security demos.",
    completed: false,
  },
  {
    id: "TSK010",
    eventId: "EV013",
    title: "Archive forensic image files on secure storage",
    description: "Post-event data backup for workshop exercises.",
    completed: true,
  },
  {
    id: "TSK011",
    eventId: "EV014",
    title: "Collect judge evaluation scorecards",
    description: "Hand over scoring sheets to the TCF team lead.",
    completed: true,
  },
];
